# Generated by Django 4.0.3 on 2022-04-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
