# Generated by Django 4.0.3 on 2022-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_customer_name_remove_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requestBook',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='rname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
