# Generated by Django 4.0.3 on 2022-04-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_request_requestbook_alter_request_rname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
