# Generated by Django 4.0.3 on 2022-04-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(default='', max_length=200)),
                ('requestBook', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
