# Generated by Django 4.0.3 on 2022-04-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_requestbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestbook',
            old_name='requestBook',
            new_name='bookrequest',
        ),
    ]
