# Generated by Django 4.0.3 on 2022-04-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_requestbook_requestbook_bookrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
    ]
