# Generated by Django 4.0.3 on 2022-04-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(max_length=200),
        ),
    ]
