# Generated by Django 4.0.3 on 2022-04-26 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0019_rename_customer_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='Customer',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='cartitems',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.cartitems'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(),
        ),
    ]
