# Generated by Django 4.0.3 on 2022-04-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_remove_order_book_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='renumber',
            field=models.IntegerField(default=0),
        ),
    ]
