# Generated by Django 4.0.3 on 2022-04-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_order_renumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
