# Generated by Django 4.0.3 on 2022-04-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_rename_user_id_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
