# Generated by Django 4.0.3 on 2022-04-28 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_order_cart_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
