# Generated by Django 4.0.3 on 2022-04-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_remove_order_cartitem_id_delete_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
